config/routes.rb
Rails.application.routes.draw do
  ### Errors
  get 'errors/not_found'
  get 'errors/forbidden'
  get 'errors/internal_server_error'

  ### API
  api_version(:module => "V1", :path => {:value => "api/v1"}) do #, :defaults => {:format => :json}
    resources :occurrences
  end

  ### Resources

  root 'overview#index'
  get 'overview', to: 'overview#index'

  resources :occurrences
  get '/occurrences_compact', to: 'occurrences#compact'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  get '/register', to: 'users#new'


  ### Error Pages
  match '/403', to: 'errors#forbidden', via: :get
  match '/404', to: 'errors#not_found', via: :get

  # resources :sessions, only: [:create]
  # delete "/sessions/dismiss", to: "sessions#logout"
  # get "/sessions/check", to: "sessions#logged_in"
end

app/models/occurrence.rb
class Occurrence < ApplicationRecord

end

app/controllers/occurrences_controller.rb
class OccurrencesController < ApplicationController
  before_action :set_occurrence, only: %i[ show edit update destroy ]
  before_action :set_ui

  # GET /occurrences or /occurrences.json
  def index
    if params['from'] && params['to']
      @occurrences = Occurrence.where(:start_time => params['from'].to_date.beginning_of_day..params['to'].to_date.end_of_day)
    else
      @occurrences = Occurrence.all
    end
  end

  def compact
    if params['day']
      @occurrences = Occurrence.where(:start_time => params['day'].to_date.beginning_of_day..params['day'].to_date.end_of_day)

      respond_to do |format|
        format.html { render "occurrences/compact", :layout => false }
      end
    end
  end

  # GET /occurrences/1 or /occurrences/1.json
  def show

    @occurrence = Occurrence.find(params[:id])

  end

  # GET /occurrences/new
  def new
    if @current_user
      @occurrence = Occurrence.new
    else
      respond_to do |format|
        flash[:warning] = 'You need to be logged in to edit Events'
        format.html { redirect_to '/login' }
        format.json { render json: {status: 'forbidden'}, status: :forbidden }
      end
    end
  end

  # GET /occurrences/1/edit
  def edit
    unless @current_user
      flash[:warning] = 'You need to be logged in to edit Events'
      respond_to do |format|
        format.html { redirect_to '/login' }
        format.json { render json: {status: 'forbidden'}, status: :forbidden }
      end
    end
  end

  # POST /occurrences or /occurrences.json
  def create
    if @current_user
      @occurrence = Occurrence.new(occurrence_params)

      respond_to do |format|
        if @occurrence.save
          format.html { redirect_to @occurrence, notice: "Occurrence was successfully created." }
          format.json { render :show, status: :created, location: @occurrence }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @occurrence.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to '/login' }
        format.json { render json: {status: 'forbidden'}, status: :forbidden }
      end
    end
  end

  # PATCH/PUT /occurrences/1 or /occurrences/1.json
  def update
    if @current_user
      respond_to do |format|
        if @occurrence.update(occurrence_params)
          format.html { redirect_to @occurrence, notice: "Occurrence was successfully updated." }
          format.json { render :show, status: :ok, location: @occurrence }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @occurrence.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to '/login' }
        format.json { render json: {status: 'forbidden'}, status: :forbidden }
      end
    end
  end

  # DELETE /occurrences/1 or /occurrences/1.json
  def destroy
    if @current_user
      @occurrence.destroy
      respond_to do |format|
        format.html { redirect_to occurrences_url, notice: "Occurrence was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      flash[:warning] = 'You need to be logged in to edit Events'
      respond_to do |format|
        format.html { redirect_to '/login' }
        format.json { render json: {status: 'forbidden'}, status: :forbidden }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_occurrence
      @occurrence = Occurrence.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def occurrence_params
      params.require(:occurrence).permit(:name, :start_time)
    end

    def set_ui
      @active_user = @current_user
      @page = 'occurrences'
    end
end

app/controllers/v1/occurrences_controller.rb
class V1::OccurrencesController < V1::BaseController
  include CurrentUserConcern

  before_action :set_occurrence, only: [:show, :update, :destroy]

  def index
    if @current_user
      if params['from'] && params['to']
        @occurrences = Occurrence.where(:start_time => params['from'].to_date.beginning_of_day..params['to'].to_date.end_of_day)
      else
        @occurrences = Occurrence.all
      end
    else
      render 'errors/forbidden', status: :forbidden
    end

    render json: @occurrences
  end

  def show
    if @current_user
      render json: @occurrence
    else
      render 'errors/forbidden', status: :forbidden
    end
  end

  def create
    if @current_user
      @occurrence = Test.new(occurrence_params)

      if @occurrence.save
        render json: @occurrence, status: :created, location: @occurrence
      else
        render json: @occurrence.errors, status: :unprocessable_entity
      end
    else
      render 'errors/forbidden', status: :forbidden
    end
  end

  private
    def set_occurrence
      @occurrence = Occurrence.find(params[:id])
    end

    def occurrence_params
      params.require(:occurrence).permit(:name, :start_time)
    end
end

app/helpers/occurrences_helper.rb
module OccurrencesHelper
end

app/views/occurrences/_form.html.erb
<%= form_with(model: occurrence, :class => 'w-50') do |form| %>
  <% if occurrence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(occurrence.errors.count, "error") %> prohibited this occurrence from being saved:</h2>

      <ul>
        <% occurrence.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :start_time %> <br>
    <%= form.datetime_select :start_time, :class => 'form-control' %>
  </div>

  <div class="actions">
    <%= link_to 'Back', occurrences_path, :class => 'btn btn-secondary text-light h-100 mt-5' %><%= form.submit :class => 'btn btn-primary text-light h-100 mt-5 mx-3' %>
  </div>
<% end %>

app/views/occurrences/compact.html.erb
<table class="table">
  <h3>
    <%= @occurrences.first.start_time.to_date.strftime('%d.%m.%Y') if @occurrences.first %>
    <%= 'No Events on this day' unless @occurrences.first %>
  </h3>
  <thead>
  <tr>
    <th>Name</th>
    <th>Time</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @occurrences.each do |occurrence| %>
    <tr>
      <td><%= occurrence.name %></td>
      <td> <%= occurrence.start_time.strftime("%T") %></td>
      <td><%= link_to I18n.translate('actions.show'), occurrence, :class => 'btn btn-sm btn-secondary text-light px-2' %>
      <%= link_to I18n.translate('actions.edit'), edit_occurrence_path(occurrence), :class => 'btn btn-sm btn-warning px-2' %>
      <%= link_to I18n.translate('actions.destroy') , occurrence, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger text-light px-2' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/occurrences/edit.html.erb
<div class="container mt-5">
  <h1>Editing Occurrence</h1>

  <%= render 'form', occurrence: @occurrence %>

  <%= link_to 'Show Occurrence', @occurrence %>
</div>

app/views/occurrences/index.html.erb
<div class="container mt-5">

  <p id="notice"><%= notice %></p>

  <h1>Occurrences</h1>

  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @occurrences.each do |occurrence| %>
      <tr>
        <td><%= occurrence.name %></td>
        <td><%= I18n.localize occurrence.start_time %></td>
        <td><%= link_to I18n.translate('actions.show'), occurrence, :class => 'btn btn-sm btn-secondary text-light px-4' %></td>
        <td><%= link_to I18n.translate('actions.edit'), edit_occurrence_path(occurrence), :class => 'btn btn-sm btn-warning px-4' %></td>
        <td><%= link_to I18n.translate('actions.destroy') , occurrence, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger text-light px-4' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to octicon("arrow-left", :height => 16, :fill => "white") + ' Back', overview_path, :class => "btn btn-secondary text-light px-4" %>
  <%= link_to octicon("plus", :height => 16, :fill => "white") + ' New Event', new_occurrence_path, :class => "btn btn-primary text-light mx-3 px-4" %>
</div>

app/views/occurrences/new.html.erb
<div class="container mt-5">
  <h1>New Occurrence</h1>

  <%= render 'form', occurrence: @occurrence %>
</div>

app/views/occurrences/show.html.erb
<div class="container mt-5">
  <p id="notice"><%= notice %></p>

  <div>
    <strong>Name:</strong>
    <div class="form-control w-50" disabled readonly><%= @occurrence.name %></div>
  </div>

  <div>
    <strong>Start time:</strong>
    <div class="form-control w-50" disabled readonly><%= @occurrence.start_time %></div>
  </div>

  <%= link_to octicon("arrow-left", :height => 16, :fill => "white") + ' Back', occurrences_path, :class => "btn btn-secondary text-light mt-5 px-4" %>
  <%= link_to octicon("pencil", :height => 16, :fill => "grey") + ' Edit', edit_occurrence_path(@occurrence), :class => "btn btn-warning mt-5 mx-3 px-4" %>

</div>